---

# clone git repository
# TODO: switch to use actual repo (NOTE: this takes a while)
- name: clone git repository containing the Data Snapshot
  git:
    repo: https://github.com/IATI/deployment.git
    dest: /home/backup-data-snapshot/small-repo
    update: yes
    version: master
