---

# tasks to complete as root
- include_tasks: root-data-snapshot.yml

# tasks to complete as not-root
- include_tasks: data-snapshot.yml
  become: true
  become_user: "{{ git_user_account_name }}"
