---

- name: Install setup dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git

- name: Install Registry Refresher apt dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - php7.0-curl
    - php7.0-cli
    - wget

# Install `gist` script for Registry Refresher
# - name: Install `gist` apt dependencies
#   apt:
#     name: "{{ item }}"
#     state: present
#     update_cache: yes
#   with_items:
#     - ruby1.9.1
#     - rubygems

# - name: Install `gist` gem dependencies
#   gem:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - gist
#     - optparse

- name: Create a non-root user - Registry Refresher
  user:
    name: registry-refresher
    comment: "Account to manage the Registry Refresher"
    createhome: yes
